global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'waiting-room'
    static_configs:
      - targets: ['waiting-room:8080']

  - job_name: 'nats'
    metrics_path: /varz
    static_configs:
      - targets: ['nats:8222']
